### ISSUE TITLE
URL Parsing Issues

### ISSUE THREAD

**Issue by hhenrichsen** [jakobottar/kyoko-bot#1]
Kyoko works for the following URLs:
```
https://www.youtube.com/watch?v=iu7wJwbLkpo
https://www.youtube.com/watch?v=iu7wJwbLkpo&t=31
https://youtu.be/iu7wJwbLkpo
```

But fails on shortened youtu.be links:
```
https://youtu.be/iu7wJwbLkpo?t=31
```

And has unknown functionality when using links with playlists on the end.

**Comment by jakobottar** [comment]
The existing code works with links with playlist tags since it only grabs the 11 characters after the first equals sign. 
Works with 
```https://www.youtube.com/watch?v=eOyX42oTy1g&list=PLf_1LRVmP-5vwgEugZs1etsuiSbVB6bnC&index=25```
